name: ci-node
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: prepara-ambiente
        uses: actions/checkout@v4
      
      - name: prepara-node
        uses: actions/setup-node@v4
        with:
          node-version: '14'
      
      - name: instala-dependencia
        run: npm install --save-dev jest supertest

      - name: executa-teste
        run: npm test